### PR TITLE
chore: clean dependencies and lint

### PR DESCRIPTION
**Pull request by rtritto**
Continue #100

### Details:
- Update/clean _dependencies_ and _devDependencies_
- Add _yml_ extension to _.eslintrc_
- Remove _comma-dangle_ eslint rule
- Remove _devInstall_
- Replace _pathname_ with _fileURLToPath_
- Add _node_ protocol
- Add entrypoint informations
- Move `@fastify/vite`, `vite` and _vite-plugins_ from _dependencies_ to _devDependencies_

Tips: use squash instead of merge to don't create a lot of commits in branch history.

### CODE REVIEW

**Comment by galvez** [comment]
> Tips: use squash instead of merge to don't create a lot of commits in branch history.

Indeed, that was a little oversight — thanks for all the work, are you on Discord by the way?

I should probably share some of the stuff I've been working on to facilitate maintenance on this repo.

**Comment by rtritto** [comment]
> Indeed, that was a little oversight — thanks for all the work, are you on Discord by the way?
I should probably share some of the stuff I've been working on to facilitate maintenance on this repo.

I sent you an email.

**Comment by rtritto** [comment]
@galvez can `devInstall` be removed from all _package.json_ of examples? (All related _devInstall dependencies_ will be merged in _dependencies_)

**Comment by rtritto** [comment]
On Windows (WSL), with _zx_, I have this error related to `npm run devinstall` of _all_ in `devinstall.mjs`: 
- npm
```console
Error: /usr/bin/env: ‘bash\r’: No such file or directory
    at file:///C:/<PROJECT_PATH>/fastify-vite/devinstall.mjs:50:12
    exit code: 127 (Command not found)
```
- yarn
```console
/mnt/c/Users/<USER>/AppData/Local/Temp/xfs-70308c6c/yarn: 2: exec: C:\Program Files\nodejs\node.exe: not found
Error: /mnt/c/Users/<USER>/AppData/Local/Temp/xfs-70308c6c/yarn: 2: exec: C:\Program Files\nodejs\node.exe: not found
    at file:///C:/<PROJECT_PATH>/fastify-vite/devinstall.mjs:50:12
    exit code: 127 (Command not found)
```

**Comment by rtritto** [comment]
@galvez can `zx` workflow be removed in favor of `standard-ci` of GitHub?

**Comment by rtritto** [comment]
@galvez in examples, IMO `vite` dependency should be moved to devDependencies. `@fastify/vite` dependency should also be moved?

**Comment by galvez** [comment]
Let me take a good hard look at all of this, but LGTM so far. I have another branch with a complete refactor of `devinstall`, so don't worry about it too much. Let's wait until I'm done with the refactor, sync with this branch, and then we worry about setting up the proper workflows for testing and QA. Thanks a million for all the work!

**Comment by galvez** [comment]
Alright, I'm close to merging my branch into this one, just as a FYI, please don't push anything else to it until I'm done 😉

**Comment by galvez** [comment]
```
To github.com:rtritto/fastify-vite.git
 ! [remote rejected] rtritto/clean-example-deps -> rtritto/clean-example-deps (permission denied)
error: failed to push some refs to 'git@github.com:rtritto/fastify-vite.git'
```

Can you give me access?

**Comment by galvez** [comment]
Nevermind — I was doing it wrong.

**Pull request merged**
