### PR TITLE
feat: SolidJS support with fastify-vite-solid renderer adapter

### PR DESCRIPTION
**Pull request by yonathan06**
https://github.com/fastify/fastify-vite/issues/24

This is a WIP

based on the React implementation fastify-vite-react (maybe should extract similar code to a shared lib) 

I don't have much experience with SolidJs and Vite, so feel free to share your thoughts

The DX looks similar to React, with `renderToString` and JSX being translated kind the same

SolidJs does provide a different approach to rendering as it doesn't use a VDOM, so maybe need to take it into considering we hydrating on the client side

with that said, SolidJs has a mature solution for SSR and client hydration, so maybe everything will go smoothly

Things to keep in mind:

1. the [solid-app-router](https://github.com/solidjs/solid-app-router) router is different than React's, maybe it doesn't work out of the box with SSR
2. Meta tags are rendered with the [solid-meta](https://github.com/solidjs/solid-meta) lib, which takes inspiration from react-helmet, but it is not 1 to 1

### CODE REVIEW

**Comment by yonathan06** [comment]
Getting this error from `solid-meta` using ES modules
```
(fastify-vite-solid ±) solidjs-base ツ npm run build

> build
> node server build

7:05:55 PM [vite] Error when evaluating SSR module /Users/yonatanbd/Code/fastify-vite/examples/solidjs-base/@app/entry/server.jsx:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/yonatanbd/Code/fastify-vite/examples/solidjs-base/node_modules/fastify-vite-solidjs/node_modules/solid-meta/dist/index.js
require() of ES modules is not supported.
require() of /Users/yonatanbd/Code/fastify-vite/examples/solidjs-base/node_modules/fastify-vite-solidjs/node_modules/solid-meta/dist/index.js from /Users/yonatanbd/Code/fastify-vite/examples/solidjs-base/node_modules/fastify-vite-solidjs/render.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/yonatanbd/Code/fastify-vite/examples/solidjs-base/node_modules/fastify-vite-solidjs/node_modules/solid-meta/package.json.

    at new NodeError (node:internal/errors:363:5)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1125:13)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/yonatanbd/Code/fastify-vite/examples/solidjs-base/node_modules/fastify-vite-solidjs/render.js:3:24)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/yonatanbd/Code/fastify-vite/examples/solidjs-base/node_modules/fastify-vite-solidjs/node_modules/solid-meta/dist/index.js
require() of ES modules is not supported.
require() of /Users/yonatanbd/Code/fastify-vite/examples/solidjs-base/node_modules/fastify-vite-solidjs/node_modules/solid-meta/dist/index.js from /Users/yonatanbd/Code/fastify-vite/examples/solidjs-base/node_modules/fastify-vite-solidjs/render.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/yonatanbd/Code/fastify-vite/examples/solidjs-base/node_modules/fastify-vite-solidjs/node_modules/solid-meta/package.json.

    at new NodeError (node:internal/errors:363:5)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1125:13)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/yonatanbd/Code/fastify-vite/examples/solidjs-base/node_modules/fastify-vite-solidjs/render.js:3:24)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32) {
  code: 'ERR_REQUIRE_ESM'
}
```

Should we fork solid-meta? 😅

**Comment by yonathan06** [comment]
https://github.com/solidjs/solid-meta/issues/3

**Comment by galvez** [comment]
Okay, I picked this up for testing and just realized I missed the bit about CJS limitation.

You can now use `npm run devinstall` from `examples/solid-base` to get the latest local packages installed there.

It modifies the behavior of devinstall.mjs a bit (but it's now much faster to work with).

I was hoping to get this as part of the next release, but unfortunately I can't spend any more time debugging this now and a new patch release for React must go out ASAP :)

We're close, I'll look into how adapt the server entry point to bundle the things we need for `render.js`.

**Comment by yonathan06** [comment]
The ssr transforming is different then the browser one, need to check how it used with the vite plugin
see here https://github.com/solidjs/solid/discussions/742

**Comment by galvez** [comment]
We got some assistance directly from @ryansolid — see latest commit, it's working now. Think getting the rest done will be smoother now (and easier to test already).

**Pull request merged**
