### PR TITLE
feat(docs): Implement select box and click-to-copy

### PR DESCRIPTION
**Pull request by davidmeirlevy**
As mentioned in the TODO.md:

Implement select box and click-to-copy like in https://stripe.com/docs/js/initializing

### CODE REVIEW

**Comment by davidmeirlevy** [comment]
@galvez you can see a demo on this page:
https://deploy-preview-63--agitated-mahavira-26f8f9.netlify.app/quickstart/vue.html

this component support slots of js, ts, sh.

**Comment by galvez** [comment]
Amazing!

Screen Shot 2022-02-03 at 17 53 20

Maybe widen the margin between button and borders? And also display "click to copy" where it says "copied" while the user is hovering the source code.

**Comment by galvez** [comment]
Otherwise LGTM!

**Comment by galvez** [comment]
Also please use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) in PR titles.

**Comment by davidmeirlevy** [comment]
@galvez I think that adding a "click to copy" test is not so elegant. 
The pointer cursor on the code might be enough, don't you think?

I've added some more examples with markdown inside the slot and actual code.

**Comment by galvez** [comment]
LGTM

**Comment by davidmeirlevy** [comment]
@galvez btw I see now that it may needs some "overflow: scroll" to contain the code in mobile.

**Pull request merged**
