### PR TITLE
fix: await userConfig to support async vite config

### LINKED ISSUE #119: TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.3

### Plugin version

5.0.0

### Node.js version

18.7

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.3

### Description

TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at resolve (node:path:1097:7)
    at resolveSPABundle (/Users/***/Projects/node/***/node_modules/@fastify/vite/config.js:219:18)
    at configure (/Users/***/Projects/node/***/node_modules/@fastify/vite/config.js:112:24)
    at async Vite.ready (/Users/**/Projects/node/***/node_modules/@fastify/vite/index.js:19:19)
    at async main (file:///Users/***/Projects/node/***/dist/server/index.js:30:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}

### Steps to Reproduce

```
instance.register(FastifyVite, {
    root: path.resolve(__dirname, '../../../'),
    dev: env.NODE_ENV === 'development',
    spa: true,
  })
```

inside vite, pass an `async` function to [`defineConfig`](https://vitejs.dev/config/#async-config)

### Expected Behavior

it should `await` the function

### PR DESCRIPTION
**Pull request by felixmosh**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

closes #119

### CODE REVIEW

**Review by Uzlopak — COMMENTED** [review]
Please add a unit test if possible

**Comment by felixmosh** [comment]
I can't run tests locally, it breaks on this
image

**Comment by Uzlopak** [comment]
I realize that this repo does not have any tests.
Nevermind. I guess @galvez will manually review it.

**Review by Uzlopak — APPROVED** [review]
Awaiting a sync function should not be error prone. It is just negligible slower.

**Comment by felixmosh** [comment]
The alternative is "not working" lib :]

**Comment by galvez** [comment]
> I realize that this repo does not have any tests.

Perhaps I should highlight this in the README — **the tests are in the package folder** and also in every individual example, which further help validate if the package is working as expected.

**Comment by Uzlopak** [comment]
@galvez 
We need a CI/CD pipeline.

**Review by galvez — APPROVED** [review]
LGTM — this doesn't require any new tests, thank you!

**Comment by galvez** [comment]
> @galvez We need a CI/CD pipeline.

That's for sure — will look into that as soon as I can!

**Pull request merged**
