### PR TITLE
chore!: move `fastify` and `vite` from deps to peerDeps

### LINKED ISSUE #98: Move `fastify` and `vite` to peer dependencies
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.12.0

### Plugin version

3.0.8

### Node.js version

16.17.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

I used [solid-hydration](https://github.com/fastify/fastify-vite/tree/dev/examples/solid-hydration) example.
`@fastify/vite` and [server.js](https://github.com/fastify/fastify-vite/blob/dev/examples/solid-hydration/server.js) use `fastify`.
`fastify` is a dependency of `@fastify/vite` and it should be installed only once (single instance dependency).
It should be moved from dependencies to peer dependencies.

Same for `vite` dependency.

### Expected Behavior

`fastify` and `vite` are in peer dependencies

### PR DESCRIPTION
**Pull request by rtritto**
Fix #98

### CODE REVIEW

**Comment by Uzlopak** [comment]
Well peerDependencies were not installed on older npm versions. Is npm which is shipped with latest node 14 installing peerDependencies?

**Comment by rtritto** [comment]
Auto install for peerDependencies was introduced from npm v7 ([source](https://stackoverflow.com/questions/35207380/how-to-install-npm-peer-dependencies-automatically)).
Node v14.0.0 use use npm v6.14.4.

**Comment by rtritto** [comment]
I updated the README

**Review by Uzlopak — APPROVED** [review]
LGTM

**Pull request merged**
