### PR TITLE
fix(hmr): fix hmr when using h2 and use merge config

### LINKED ISSUE #109: Websocket can not connect when using https fastify
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

^4.17.0

### Plugin version

^4.0.0

### Node.js version

v18.16.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.3.1 (22E261)

### Description

App served via the `@fastify/vite` plugin does not work when configuring fastify to use https and http2

### Steps to Reproduce

Reproduction repository: https://github.com/benatshippabo/fastify-vite-test

```sh
git clone https://github.com/benatshippabo/fastify-vite-test.git
cd fastify-vite-test
yarn
yarn ts-node devserver.ts
```

- go to https://localhost:3000
- check console for errors about not being able to connect to `wss://localhost:24678/`
- try to edit `./src/App.tsx`
- notice hmr does not work

### Expected Behavior

Going to https://localhost:3000 and editing `./src/App.tsx` hot reloads properly with no errors about connectivity issues to the websocket.

### PR DESCRIPTION
**Pull request by benatshippabo**
#### Description

[Sets vite hmr server to use fastify.](https://vitejs.dev/config/server-options.html#server-hmr:~:text=When%20server.hmr,a%20single%20port.) This fixes #109 and will allow users to use https and h2 with @fastify/vite. Also uses `mergeConfig` and `defineConfig` for hassle free recursive config merging and type safe config declarations.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by benatshippabo** [comment]
@galvez there is a task to run the benchmark, but I don't see benchmark listed as a script in the package.json.

**Comment by galvez** [comment]
Thank you! Let me run the test suite and I'll merge and release this.

**Comment by galvez** [comment]
> @galvez there is a task to run the benchmark, but I don't see benchmark listed as a script in the package.json.

Yeah, that needs some maintenance work.

**Comment by benatshippabo** [comment]
@galvez any feedback for this pull request? Please let me know if anything needs to be adjusted

**Comment by galvez** [comment]
Hey there — I should push out a new release with this by Monday. Thank you!

**Pull request merged**
